# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-13 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('artist', models.CharField(max_length=30)),
                ('catgry', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
