# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-13 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='artist',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='catgry',
            field=models.TextField(max_length=10),
        ),
    ]
