# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-14 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160113_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dwn',
            field=models.URLField(),
        ),
    ]
