# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-14 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160114_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
